import { writeFileSync, readFileSync, existsSync, mkdirSync } from 'fs';
import { join } from 'path';
import { randomBytes } from 'crypto';

const ROOT_DIR = process.cwd();

/**
 * Validate Anthropic API key by making a minimal test call
 */
export async function validateAnthropicKey(key) {
  try {
    const response = await fetch('https://api.anthropic.com/v1/messages', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'x-api-key': key,
        'anthropic-version': '2023-06-01',
      },
      body: JSON.stringify({
        model: 'claude-3-haiku-20240307',
        max_tokens: 1,
        messages: [{ role: 'user', content: 'Hi' }],
      }),
    });

    if (response.status === 401) {
      return { valid: false, error: 'Invalid API key' };
    }
    if (response.status === 400) {
      // Bad request but key is valid (e.g., rate limit, model error)
      return { valid: true };
    }
    if (response.ok) {
      return { valid: true };
    }
    return { valid: false, error: `HTTP ${response.status}` };
  } catch (error) {
    return { valid: false, error: error.message };
  }
}

/**
 * Generate .pi/agent/models.json for providers not built into PI.
 * PI resolves the apiKey field as an env var name at runtime ($ENV_VAR).
 */
export function writeModelsJson(providerName, { baseUrl, apiKey, api, models }) {
  const config = {
    providers: {
      [providerName]: {
        baseUrl,
        apiKey,
        api: api || 'openai-completions',
        models: models.map((m) => ({ id: m })),
      },
    },
  };
  const dir = join(ROOT_DIR, '.pi', 'agent');
  mkdirSync(dir, { recursive: true });
  writeFileSync(join(dir, 'models.json'), JSON.stringify(config, null, 2));
}

/**
 * Write .env file at project root
 */
export function writeEnvFile(config) {
  const {
    githubToken,
    githubOwner,
    githubRepo,
    telegramBotToken,
    telegramWebhookSecret,
    ghWebhookSecret,
    llmProvider,
    llmModel,
    providerEnvKey,
    providerApiKey,
    openaiApiKey,
    openaiBaseUrl,
    telegramChatId,
    telegramVerification,
    appUrl,
    appHostname,
  } = config;

  // Build the provider API key line(s)
  // Always write the provider's key; also write OPENAI_API_KEY if it's a separate key (for Whisper)
  let apiKeyLines = `# LLM API key (${providerEnvKey})\n${providerEnvKey}=${providerApiKey}`;
  if (providerEnvKey !== 'OPENAI_API_KEY') {
    apiKeyLines += `\n\n# OpenAI API key for Whisper voice transcription (optional)\nOPENAI_API_KEY=${openaiApiKey || ''}`;
  }
  apiKeyLines += `\n\n# OpenAI-compatible base URL (optional, event handler only)\nOPENAI_BASE_URL=${openaiBaseUrl || ''}`;

  // Generate AUTH_SECRET (32 random bytes, base64 encoded)
  const authSecret = randomBytes(32).toString('base64');

  const envContent = `# thepopebot Configuration
# Generated by setup wizard

# App URL and hostname (used by Traefik for routing)
APP_URL=${appUrl || ''}
APP_HOSTNAME=${appHostname || ''}

# Auth.js secret (used for session encryption)
AUTH_SECRET=${authSecret}
AUTH_TRUST_HOST=true

# GitHub Personal Access Token (fine-grained: Actions, Administration, Contents, Metadata, Pull requests)
GH_TOKEN=${githubToken}

# Repository info
GH_OWNER=${githubOwner}
GH_REPO=${githubRepo}

# LLM provider and model (used by both Event Handler and Docker Agent)
LLM_PROVIDER=${llmProvider}
LLM_MODEL=${llmModel}

# Telegram bot token from @BotFather
TELEGRAM_BOT_TOKEN=${telegramBotToken || ''}

# Telegram webhook secret (validates requests are from Telegram)
TELEGRAM_WEBHOOK_SECRET=${telegramWebhookSecret || ''}

# Telegram chat ID (restricts bot to this chat only)
TELEGRAM_CHAT_ID=${telegramChatId || ''}

# Telegram verification code (used during setup, can be removed after)
TELEGRAM_VERIFICATION=${telegramVerification || ''}

# Secret for GitHub Actions webhook auth (must match GH_WEBHOOK_SECRET secret)
GH_WEBHOOK_SECRET=${ghWebhookSecret}

${apiKeyLines}

# thepopebot version (used by docker-compose and run-job for image tags)
THEPOPEBOT_VERSION=${getThepopebotVersion()}
`;

  const envPath = join(ROOT_DIR, '.env');
  writeFileSync(envPath, envContent);
  return envPath;
}

function getThepopebotVersion() {
  try {
    const pkgPath = join(ROOT_DIR, 'node_modules', 'thepopebot', 'package.json');
    const pkg = JSON.parse(readFileSync(pkgPath, 'utf8'));
    return pkg.version;
  } catch {
    return 'latest';
  }
}

/**
 * Update a single variable in an existing .env file
 */
export function updateEnvVariable(key, value) {
  const envPath = join(ROOT_DIR, '.env');
  if (!existsSync(envPath)) {
    throw new Error('.env file not found. Run npm run setup first.');
  }

  let content = readFileSync(envPath, 'utf-8');
  const regex = new RegExp(`^${key}=.*$`, 'm');

  if (regex.test(content)) {
    content = content.replace(regex, `${key}=${value}`);
  } else {
    content = content.trimEnd() + `\n${key}=${value}\n`;
  }

  writeFileSync(envPath, content);
  return envPath;
}
