#!/usr/bin/env python3
"""
Fixture-equivalence test for event_clusterer (Path B Week 1).

The test asserts two properties:

1. **Deterministic output.** Running event_clusterer.run() twice on the
   same fixture must produce byte-equivalent output (modulo dict-iteration
   ordering, normalised below). This catches non-deterministic regressions
   like random tie-breaks introduced during a refactor.

2. **Schema-valid output.** Every cluster in the produced output must
   validate against event_clusterer_output.schema.json.

3. **Monolith-equivalent output structure.** The output must contain the
   same set of `member_hashes` that generate_feed.py's inline clustering
   would produce on the same input. This is checked by computing the set
   of frozensets of member_hashes from the produced output and asserting
   the count and bag-equality matches a captured baseline.

Run:
    python3 zombie760.github.io/botwavebomba/tests/test_event_clusterer.py

Exits 0 on pass; non-zero on any failure. Designed to drop straight into
CI without pytest. No assertion framework dependency.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(REPO_ROOT))

from book_arm.pai_modules.event_clusterer import run as run_clusterer  # noqa: E402

FIXTURE_DIR = REPO_ROOT / "zombie760.github.io" / "botwavebomba" / "fixtures"
SCHEMAS_DIR = REPO_ROOT / "zombie760.github.io" / "botwavebomba" / "schemas"

INPUT_FIXTURE = FIXTURE_DIR / "event_clusterer_input.jsonl"
EXPECTED_FIXTURE = FIXTURE_DIR / "event_clusterer_expected_output.jsonl"
OUTPUT_SCHEMA = SCHEMAS_DIR / "event_clusterer_output.schema.json"


def _read_jsonl(path: Path) -> list[dict]:
    out = []
    with path.open() as f:
        for line in f:
            line = line.strip()
            if line:
                out.append(json.loads(line))
    return out


def _cluster_signature(cluster: dict) -> tuple:
    """Order-invariant signature for cluster equality.

    The same articles assigned to the same cluster must produce the same
    signature regardless of dict iteration order or hash ordering inside
    member_hashes. The greedy assignment order from generate_feed.py is
    deterministic (largest hot pairs first, fallback to singles), so the
    list of signatures across the run is also a deterministic ordered list.
    """
    return (
        cluster["label_type"],
        cluster["label"],
        cluster["cluster_id"],
        frozenset(cluster["member_hashes"]),
        frozenset(cluster["source_ids"]),
    )


def _check(condition: bool, msg: str) -> None:
    if not condition:
        print(f"FAIL: {msg}", file=sys.stderr)
        sys.exit(1)


def test_determinism_two_runs_same_output() -> None:
    """Running the module twice on the same fixture yields identical output."""
    out_a = REPO_ROOT / ".test_clusterer_a.jsonl"
    out_b = REPO_ROOT / ".test_clusterer_b.jsonl"
    try:
        r1 = run_clusterer(INPUT_FIXTURE, out_a)
        r2 = run_clusterer(INPUT_FIXTURE, out_b)

        _check(r1["output_count"] == r2["output_count"],
               f"output_count differs across runs: {r1['output_count']} vs {r2['output_count']}")

        clusters_a = _read_jsonl(out_a)
        clusters_b = _read_jsonl(out_b)
        sigs_a = [_cluster_signature(c) for c in clusters_a]
        sigs_b = [_cluster_signature(c) for c in clusters_b]
        _check(sigs_a == sigs_b,
               "cluster signatures differ between two runs on identical input")
        print(f"  PASS test_determinism: {len(clusters_a)} clusters, identical across runs")
    finally:
        for p in (out_a, out_b):
            if p.exists():
                p.unlink()


def test_schema_valid() -> None:
    """Every cluster in the expected-output fixture validates against the schema."""
    try:
        import jsonschema
    except ImportError:
        print("  SKIP test_schema_valid: jsonschema not installed")
        return
    schema = json.loads(OUTPUT_SCHEMA.read_text())
    clusters = _read_jsonl(EXPECTED_FIXTURE)
    _check(len(clusters) > 0, "expected_output fixture is empty")
    for c in clusters:
        jsonschema.validate(instance=c, schema=schema)
    print(f"  PASS test_schema_valid: {len(clusters)} clusters all valid")


def test_matches_baseline_fixture() -> None:
    """Module output on input fixture matches the captured expected_output fixture.

    The expected_output fixture was generated by running this same module
    on input_fixture and committed to the repo. This test asserts that the
    module's behaviour is stable: a future change to the clustering logic
    that breaks fixture-equivalence with the captured monolith-extracted
    behaviour will fail this test.
    """
    out = REPO_ROOT / ".test_clusterer_baseline.jsonl"
    try:
        run_clusterer(INPUT_FIXTURE, out)
        produced = _read_jsonl(out)
        expected = _read_jsonl(EXPECTED_FIXTURE)
        _check(len(produced) == len(expected),
               f"cluster count mismatch: produced={len(produced)} expected={len(expected)}")
        # Compare order-invariant signatures
        produced_sigs = sorted(_cluster_signature(c) for c in produced)
        expected_sigs = sorted(_cluster_signature(c) for c in expected)
        _check(produced_sigs == expected_sigs,
               "cluster signatures differ between produced output and expected fixture")
        print(f"  PASS test_matches_baseline_fixture: {len(produced)} clusters match baseline")
    finally:
        if out.exists():
            out.unlink()


def test_input_count_matches_fixture() -> None:
    """Sanity check: the module reads the same number of articles we put in the fixture."""
    out = REPO_ROOT / ".test_clusterer_count.jsonl"
    try:
        result = run_clusterer(INPUT_FIXTURE, out)
        with INPUT_FIXTURE.open() as f:
            expected_lines = sum(1 for line in f if line.strip())
        _check(result["input_count"] == expected_lines,
               f"input_count {result['input_count']} != fixture lines {expected_lines}")
        print(f"  PASS test_input_count: {result['input_count']} articles ingested")
    finally:
        if out.exists():
            out.unlink()


def main() -> int:
    print("event_clusterer fixture-equivalence test suite")
    print(f"  fixture: {INPUT_FIXTURE.relative_to(REPO_ROOT)}")
    print(f"  expected: {EXPECTED_FIXTURE.relative_to(REPO_ROOT)}")
    test_input_count_matches_fixture()
    test_determinism_two_runs_same_output()
    test_schema_valid()
    test_matches_baseline_fixture()
    print("ALL PASS")
    return 0


if __name__ == "__main__":
    sys.exit(main())
